apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-product
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sol-aws/eks-msa.git
    targetRevision: main
    path: msa/product/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: soldesk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true